import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import Stripe from 'https://esm.sh/stripe@14?target=deno'
import { corsHeaders, jsonResponse } from '../_shared/cors.ts'

// Monthly cron. For each org that has referred end-users, compute 40% of the
// net MRR generated by those users last month and write an affiliate_payouts
// row. Actual transfer is left as a follow-up (Stripe Connect onboarding for
// affiliate Express accounts); for v1 the row is enough to drive a manual
// payout dashboard.
//
// Optional body: { period_start: 'YYYY-MM-DD', period_end: 'YYYY-MM-DD' }.
// Defaults to the previous calendar month.
const COMMISSION_RATE = 0.4

function previousMonthRange(today: Date) {
  const first = new Date(today.getFullYear(), today.getMonth() - 1, 1)
  const last = new Date(today.getFullYear(), today.getMonth(), 0)
  return { period_start: first.toISOString().slice(0, 10), period_end: last.toISOString().slice(0, 10) }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders })

  try {
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
    const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const STRIPE_KEY = Deno.env.get('STRIPE_SECRET_KEY')!
    if (!STRIPE_KEY) throw new Error('STRIPE_SECRET_KEY not set')

    const admin = createClient(SUPABASE_URL, SERVICE_ROLE)
    const stripe = new Stripe(STRIPE_KEY, { apiVersion: '2024-11-20.acacia' })

    const body = await req.json().catch(() => ({}))
    const { period_start, period_end } = body.period_start && body.period_end
      ? body
      : previousMonthRange(new Date())

    const periodStartTs = Math.floor(new Date(period_start + 'T00:00:00Z').getTime() / 1000)
    const periodEndTs = Math.floor(new Date(period_end + 'T23:59:59Z').getTime() / 1000)

    // For every org that referred someone, sum the net MRR from those users.
    const { data: referredRows, error: refErr } = await admin
      .from('profiles')
      .select('id, stripe_customer_id, referred_by_org_id')
      .not('referred_by_org_id', 'is', null)
      .not('stripe_customer_id', 'is', null)
    if (refErr) throw refErr

    const byOrg = new Map<string, string[]>()
    for (const row of referredRows ?? []) {
      const arr = byOrg.get(row.referred_by_org_id!) ?? []
      arr.push(row.stripe_customer_id!)
      byOrg.set(row.referred_by_org_id!, arr)
    }

    const report: Array<{ org_id: string; users: number; gross: number; commission: number }> = []

    for (const [orgId, customerIds] of byOrg) {
      let gross = 0
      for (const customerId of customerIds) {
        // Sum successful charges in the period for this customer.
        const charges = await stripe.charges.list({
          customer: customerId,
          created: { gte: periodStartTs, lte: periodEndTs },
          limit: 100,
        })
        for (const ch of charges.data) {
          if (ch.paid && !ch.refunded) {
            gross += ch.amount - (ch.amount_refunded ?? 0)
          }
        }
      }
      const commission = Math.floor(gross * COMMISSION_RATE)

      const { error: insErr } = await admin
        .from('affiliate_payouts')
        .upsert(
          {
            org_id: orgId,
            period_start,
            period_end,
            referred_user_count: customerIds.length,
            gross_mrr_cents: gross,
            commission_cents: commission,
            status: 'pending',
          },
          { onConflict: 'org_id,period_start,period_end' },
        )
      if (insErr) console.error('failed to upsert payout for', orgId, insErr)

      report.push({ org_id: orgId, users: customerIds.length, gross, commission })
    }

    return jsonResponse({ ok: true, period_start, period_end, orgs: report.length, report })
  } catch (e) {
    console.error('affiliate-payout error', e)
    return jsonResponse({ error: (e as Error).message }, 500)
  }
})
